// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutSection: typeof import('./components/Organisms/Sections/AboutSection.vue')['default']
    BaseButton: typeof import('./components/Atoms/BaseButton.vue')['default']
    BaseHero: typeof import('./components/Atoms/BaseHero.vue')['default']
    BaseSection: typeof import('./components/Atoms/BaseSection.vue')['default']
    BaseSubtitle: typeof import('./components/Atoms/BaseSubtitle.vue')['default']
    BaseTitle: typeof import('./components/Atoms/BaseTitle.vue')['default']
    HighlightSection: typeof import('./components/Organisms/Sections/HighlightSection.vue')['default']
    InitiativesSection: typeof import('./components/Organisms/Sections/InitiativesSection.vue')['default']
    LandingFooter: typeof import('./components/Organisms/Footers/LandingFooter.vue')['default']
    LandingHeader: typeof import('./components/Organisms/Headers/LandingHeader.vue')['default']
    MenuItem: typeof import('./components/Atoms/MenuItem.vue')['default']
    README: typeof import('./components/README.md')['default']
    RoadmapSection: typeof import('./components/Organisms/Sections/RoadmapSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialIcon: typeof import('./components/Atoms/SocialIcon.vue')['default']
    SocialSection: typeof import('./components/Organisms/Sections/SocialSection.vue')['default']
  }
}
